CREATE TABLE IF NOT EXISTS user_profiles (
    id VARCHAR(191) PRIMARY KEY,
    email VARCHAR(191) UNIQUE NOT NULL,
    phone_number VARCHAR(191) UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    avatar_url VARCHAR(255),
    cover_url VARCHAR(255),
    gender INT,
    date_of_birth DATE,
    bio VARCHAR(500),
    timezone VARCHAR(255),
    locale VARCHAR(255),
    last_active_at DATETIME,
    is_online BOOLEAN DEFAULT FALSE,
    account_status VARCHAR(50) DEFAULT 'ACTIVE',
    warning_count INT DEFAULT 0,
    created_at DATETIME,
    updated_at DATETIME
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
