server:
  port: 8080


spring:
  config:
    import: optional:file:.env[.properties], optional:file:Backend/auth-service/.env[.properties]
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:alo_auth_db}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # Ép Hibernate sử dụng đúng phương ngữ cho MariaDB đời cũ để tránh lỗi cú pháp
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    # Tạm thời tắt nếu bạn chưa chạy Eureka Server để tránh log lỗi liên tục
    enabled: true
  instance:
    prefer-ip-address: true

# Cấu hình JWT Custom
jwt:
  secret: ${JWT_SECRET:MsHrNEtyzJ1VU7uKnh6BSgwnRu9IlzR78hlhM3eq8KK}

# Cấu hình Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-southeast-1}
    s3:
      bucket: ${AWS_S3_BUCKET:btl-alo-chat}

google:
  client-id: ${GOOGLE_CLIENT_ID}
