server:
  port: 8888

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  codec:
    max-in-memory-size: 105MB
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: contact-service
              uri: lb://CONTACT-SERVICE
              predicates:
                - Path=/api/v1/contacts/**

            - id: group-service
              uri: lb://GROUP-SERVICE
              predicates:
                - Path=/api/v1/groups/**

            - id: message-service
              uri: lb://MESSAGE-SERVICE
              predicates:
                - Path=/api/v1/messages/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**

            - id: chatbot-service
              uri: lb://CHATBOT-SERVICE
              predicates:
                - Path=/api/v1/chatbot/**
                
            - id: realtime-service
              uri: lb://REALTIME-SERVICE
              predicates:
                - Path=/socket.io/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET:MsHrNEtyzJ1VU7uKnh6BSgwnRu9IlzR78hlhM3eq8KK}