server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api-gateway/auth-service/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1

            - id: contact-service
              uri: lb://CONTACT-SERVICE
              predicates:
                - Path=/api-gateway/contact-service/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1

            - id: group-service
              uri: lb://GROUP-SERVICE
              predicates:
                - Path=/api-gateway/group-service/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1

            - id: message-service
              uri: lb://MESSAGE-SERVICE
              predicates:
                - Path=/api-gateway/message-service/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api-gateway/notification-service/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1

            - id: chatbot-service
              uri: lb://CHATBOT-SERVICE
              predicates:
                - Path=/api-gateway/chatbot-service/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
