server:
  port: 8082
  servlet:
    context-path: /group-service

spring:
  application:
    name: group-service

  datasource:
    url: jdbc:mariadb://localhost:3306/alo_group_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
