server:
  port: ${PORT:8088}

spring:
  application:
    name: report-service
  rabbitmq:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USER}
      password: ${RABBITMQ_PASSWORD}
  mongodb:
    uri: ${MONGODB_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
