/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#f2f4f8",
        "inverse-on-surface": "#9c9d9e",
        "secondary-fixed": "#dce2f3",
        "surface-container": "#ebeef0",
        "on-primary-container": "#4b5263",
        "surface-bright": "#f9f9fa",
        "surface-container-low": "#f2f4f5",
        "surface-tint": "#575e70",
        "inverse-surface": "#0c0e0f",
        "tertiary-fixed-dim": "#e3e5e9",
        "on-tertiary-fixed-variant": "#63666a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ced4e4",
        "primary-fixed": "#dce2f7",
        error: "#9f403d",
        outline: "#757c7f",
        "on-tertiary-fixed": "#474a4d",
        "tertiary-fixed": "#f2f4f8",
        "on-secondary-fixed-variant": "#555c69",
        "on-secondary-fixed": "#39404c",
        background: "#f9f9fa",
        "on-tertiary-container": "#595c5f",
        "on-background": "#2d3336",
        "on-error": "#fff7f6",
        "surface-variant": "#dde3e7",
        "on-primary": "#f7f7ff",
        "on-surface-variant": "#5a6063",
        "error-container": "#fe8983",
        "surface-container-high": "#e4e9ec",
        "tertiary-dim": "#505357",
        secondary: "#585f6d",
        "on-surface": "#2d3336",
        "on-primary-fixed-variant": "#545b6d",
        "primary-dim": "#4b5264",
        "outline-variant": "#adb3b6",
        "secondary-dim": "#4c5361",
        "on-secondary": "#f8f8ff",
        tertiary: "#5c5f63",
        "primary-container": "#dce2f7",
        "on-error-container": "#752121",
        "on-tertiary": "#f7f9fd",
        surface: "#f9f9fa",
        "error-dim": "#4e0309",
        "inverse-primary": "#d9dff5",
        "surface-dim": "#d3dbdf",
        primary: "#575e70",
        "surface-container-highest": "#dde3e7",
        "secondary-container": "#dce2f3",
        "primary-fixed-dim": "#ced4e9",
        "on-secondary-container": "#4b525f",
        "on-primary-fixed": "#383f50",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
